version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
      - ./temp:/app/temp
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/system/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - video-api-network

  redis:
    image: redis:7-alpine
    container_name: video-api-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - video-api-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-api-worker
    restart: unless-stopped
    command: ["python", "-m", "src.worker"]
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
      - ./temp:/app/temp
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - api
    networks:
      - video-api-network

volumes:
  redis-data:

networks:
  video-api-network:
    driver: bridge
